In [1]:
import numpy as np

In [6]:
# Creating arrays
a = np.array([1,2,3])
n = np.array([(1.5,2,3), (4,5,6)], dtype=float)


[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [9]:
# Initial placeholders
np.zeros((3,3)) #Create an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3,4), dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
np.arange(10,25,5) #Create an array of evenly spaced values (step value)

array([10, 15, 20])

In [19]:
np.linspace(0,10,5, dtype=np.int16) #Create an array of evenly spaced values (number of samples)

array([ 0,  2,  5,  7, 10], dtype=int16)

In [20]:
np.full((2,2),7) #Create a constant array

array([[7, 7],
       [7, 7]])

In [21]:
np.eye(2) #Create a 2X2 identity matrix

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.random((2,2)) #Create an array with random values

array([[0.79514062, 0.49855004],
       [0.06860696, 0.29321923]])

In [26]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])