In [2]:
import numpy as np

In [3]:
# Creating arrays
a = np.array([1,2,3])
n = np.array([(1.5,2,3), (4,5,6)], dtype=float)


In [9]:
# Initial placeholders
np.zeros((3,3)) #Create an array of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((2,3,4), dtype=np.int16) #Create an array of ones

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [11]:
np.arange(10,25,5) #Create an array of evenly spaced values (step value)

array([10, 15, 20])

In [19]:
np.linspace(0,10,5, dtype=np.int16) #Create an array of evenly spaced values (number of samples)

array([ 0,  2,  5,  7, 10], dtype=int16)

In [20]:
np.full((2,2),7) #Create a constant array

array([[7, 7],
       [7, 7]])

In [21]:
np.eye(2) #Create a 2X2 identity matrix

array([[1., 0.],
       [0., 1.]])

In [25]:
np.random.random((2,2)) #Create an array with random values

array([[0.79514062, 0.49855004],
       [0.06860696, 0.29321923]])

In [26]:
np.empty((3,2)) #Create an empty array

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

In [5]:
# Inspecting the array
a = np.random.random((3,3))
a.shape

(3, 3)

In [6]:
len(a) # length of array

3

In [7]:
a.ndim # number of array dimensions

2

In [10]:
a.dtype # data type of array

dtype('float64')

In [13]:
a = np.random.uniform(0,50,(3,3)) # Random values between interval
a.astype(int) # Load the values as a different type

array([[35, 27, 37],
       [17,  4, 24],
       [11,  2,  0]])

In [17]:
# Data types
np.int64
np.float32
bool
object
np.string_
np.unicode_

numpy.str_

In [20]:
# Array mathematics
a = np.random.random((3,3))
b = np.random.uniform(1,100,(3,3))
a - b # Subtract

array([[-93.00490845, -87.3667325 , -49.5379698 ],
       [ -0.80920514, -78.81094341, -60.51399406],
       [-95.85100802, -56.0098385 , -72.12394634]])

In [21]:
a + b # Addition

array([[94.56803838, 88.36485646, 51.41748535],
       [ 1.23789784, 79.64388666, 60.5630272 ],
       [97.5988113 , 56.44037753, 73.18149541]])

In [22]:
np.add(a,b) #Addition

array([[94.56803838, 88.36485646, 51.41748535],
       [ 1.23789784, 79.64388666, 60.5630272 ],
       [97.5988113 , 56.44037753, 73.18149541]])

In [23]:
np.subtract(a,b) #Subtract

array([[-93.00490845, -87.3667325 , -49.5379698 ],
       [ -0.80920514, -78.81094341, -60.51399406],
       [-95.85100802, -56.0098385 , -72.12394634]])

In [24]:
a / b # Divide

array([[0.00833345, 0.00567982, 0.01861728],
       [0.20941433, 0.00525666, 0.00040497],
       [0.00903492, 0.00382871, 0.00727811]])

In [25]:
np.divide(a, b) # Divide

array([[0.00833345, 0.00567982, 0.01861728],
       [0.20941433, 0.00525666, 0.00040497],
       [0.00903492, 0.00382871, 0.00727811]])

In [26]:
a * b # Multiply

array([[73.30022189, 43.85047753, 47.43683708],
       [ 0.21939453, 32.99597048,  1.48419651],
       [84.52805702, 12.10355172, 38.41690852]])

In [27]:
np.multiply(a, b) # Multiply

array([[73.30022189, 43.85047753, 47.43683708],
       [ 0.21939453, 32.99597048,  1.48419651],
       [84.52805702, 12.10355172, 38.41690852]])

In [28]:
np.exp(a) # Exponentiation

array([[2.18488887, 1.64717547, 2.55936141],
       [1.23905173, 1.51660097, 1.02481957],
       [2.39624191, 1.2401961 , 1.6968516 ]])

In [29]:
np.sqrt(a) # Square root

array([[0.88406163, 0.70644319, 0.96941105],
       [0.46297554, 0.64534613, 0.15657767],
       [0.93482706, 0.46397146, 0.72716885]])

In [30]:
np.sin(a) # Sine values of an array

array([[0.70439111, 0.47860214, 0.80741522],
       [0.21270878, 0.4045362 , 0.02451411],
       [0.76683899, 0.21361073, 0.50447562]])

In [31]:
np.cos(a) # Element wise cosine

array([[0.70981206, 0.87803189, 0.58998362],
       [0.97711564, 0.91452198, 0.99969948],
       [0.64183951, 0.97691886, 0.86342594]])

In [32]:
np.log(a) # Logarithm

array([[-0.246457  , -0.69502498, -0.06213312],
       [-1.54016211, -0.87593694, -3.70840615],
       [-0.13478745, -1.53586448, -0.63719315]])

In [33]:
a.dot(b)

array([[164.70902364, 161.05019996, 137.94005201],
       [ 22.90043127,  53.20812954,  37.8134841 ],
       [133.32616111, 123.57171416,  95.56157316]])

In [34]:
# Comparison
a == b # Element wise comparison

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [35]:
a < 2 # Element wise comparison

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [39]:
a = np.random.uniform(1,10,(2,2))
b = a
np.array_equal(a,b) # Check if one array is equal to the other

True

In [40]:
# Aggregate functions
a.sum() # Array sum

27.771303197631088

In [41]:
a.min() # Array min

1.4453113678570653

In [42]:
a.max() # Array max

8.98674840678035

In [43]:
a.mean() # Array elements mean

6.942825799407772

In [46]:
np.median(a) # Median

8.669621711496836

In [49]:
np.std(a) # Standard deviation

3.177837545835287